version: '3'
services:
  proxy-server:
    build:
      context: .
      dockerfile: Dockerfile-proxy-server
    volumes:
      - ${PWD}/nginx.conf:/nginx.conf:ro
      - ./certs:/certs:ro
    ports:
      - "443:443"
      - "80:80"
    command: ["sh", "/auto-reload-nginx.sh"]